from __future__ import annotations

import random

HORROR_TITLES: list[str] = [
    # --- Classic Horror Films ---
    "The Shining",
    "The Exorcist",
    "Psycho",
    "A Nightmare on Elm Street",
    "Halloween",
    "The Texas Chain Saw Massacre",
    "Alien",
    "The Thing",
    "Rosemary's Baby",
    "The Omen",
    "Poltergeist",
    "Carrie",
    "The Amityville Horror",
    "Jaws",
    "An American Werewolf in London",
    "Hellraiser",
    "Child's Play",
    "Friday the 13th",
    "Scream",
    "The Blair Witch Project",
    # --- Modern Horror Films ---
    "Hereditary",
    "Midsommar",
    "Get Out",
    "Us",
    "The Babadook",
    "It Follows",
    "The Witch",
    "A Quiet Place",
    "The Conjuring",
    "The Conjuring 2",
    "Annabelle",
    "Insidious",
    "Sinister",
    "The Purge",
    "Don't Breathe",
    "Ready or Not",
    "Barbarian",
    "Nope",
    "Pearl",
    "X",
    "Smile",
    "Talk to Me",
    "The Black Phone",
    "M3GAN",
    "Malignant",
    "Terrifier",
    "Terrifier 2",
    "Bones and All",
    "Fresh",
    "Watcher",
    "The Menu",
    "Bodies Bodies Bodies",
    "Scream VI",
    "Skinamarink",
    "Incantation",
    "The Night House",
    "Saint Maud",
    "His House",
    "Host",
    "Possessor",
    "Color Out of Space",
    "The Lighthouse",
    "Doctor Sleep",
    "Crawl",
    "Brightburn",
    "Ma",
    "The Invisible Man",
    "Candyman",
    "Old",
    "Last Night in Soho",
    "Titane",
    "Lamb",
    "Censor",
    "The Sadness",
    "Dashcam",
    "Speak No Evil",
    "Infinity Pool",
    "Knock at the Cabin",
    "Evil Dead Rise",
    # --- Horror Franchises & Sequels ---
    "Saw",
    "Saw II",
    "The Ring",
    "The Grudge",
    "Final Destination",
    "Paranormal Activity",
    "It",
    "It Chapter Two",
    "The Nun",
    "A Quiet Place Part II",
    "The Exorcist: Believer",
    "Prey",
    "Orphan",
    "Orphan: First Kill",
    "28 Days Later",
    "World War Z",
    "Train to Busan",
    "The Wailing",
    "Ringu",
    "Ju-On: The Grudge",
    "Audition",
    "Battle Royale",
    "Suspiria",
    "The Fly",
    "Re-Animator",
    "Braindead",
    "Tucker and Dale vs Evil",
    "Cabin in the Woods",
    "The Descent",
    "Dog Soldiers",
    "Eden Lake",
    "Martyrs",
    "Inside",
    "Raw",
    "[REC]",
    "The Orphanage",
    "Pan's Labyrinth",
    "The Devil's Backbone",
    "Let the Right One In",
    # --- Horror Video Games ---
    "Silent Hill",
    "Silent Hill 2",
    "Silent Hill 3",
    "Resident Evil",
    "Resident Evil 2",
    "Resident Evil 4",
    "Resident Evil Village",
    "Fatal Frame",
    "Fatal Frame II: Crimson Butterfly",
    "Five Nights at Freddy's",
    "Five Nights at Freddy's 2",
    "Five Nights at Freddy's: Security Breach",
    "Amnesia: The Dark Descent",
    "Amnesia: Rebirth",
    "Outlast",
    "Outlast 2",
    "P.T.",
    "Dead Space",
    "Dead Space 2",
    "SOMA",
    "Layers of Fear",
    "Visage",
    "Devotion",
    "Detention",
    "Little Nightmares",
    "Little Nightmares II",
    "Inside",
    "Limbo",
    "Phasmophobia",
    "Lethal Company",
    "Doki Doki Literature Club",
    "Poppy Playtime",
    "Bendy and the Ink Machine",
    "The Backrooms",
    "SCP: Containment Breach",
    "Slender: The Eight Pages",
    "Alien: Isolation",
    "Until Dawn",
    "The Quarry",
    "Man of Medan",
    "The Dark Pictures: House of Ashes",
    "Alan Wake",
    "Alan Wake 2",
    "Control",
    "Condemned: Criminal Origins",
    "F.E.A.R.",
    "System Shock",
    "System Shock 2",
    "Cry of Fear",
    "Darkwood",
    "Signalis",
    "Madison",
    "The Evil Within",
    "The Evil Within 2",
    "Dying Light",
    "The Forest",
    "Sons of the Forest",
    "Subnautica",
    "Returnal",
    "Elden Ring",
    "Bloodborne",
    "Dark Souls",
    "Diablo",
    "Dead by Daylight",
    "The Callisto Protocol",
    "Scorn",
    "Mundaun",
    "Iron Lung",
    "Content Warning",
    "Observation",
    "Soma",
    "Oxenfree",
    "Night in the Woods",
    "What Remains of Edith Finch",
    "Inscryption",
    "The Stanley Parable",
    "Undertale",
    "Hello Neighbor",
    "Granny",
    "Among Us",
    "Resident Evil 7: Biohazard",
    "The Last of Us",
    "BioShock",
    "Half-Life 2: Ravenholm",
    "Luigi's Mansion",
    "Eternal Darkness: Sanity's Requiem",
    "Clock Tower",
    "Rule of Rose",
    "Haunting Ground",
    "Siren",
    "Kuon",
    "ObsCure",
]

assert len(HORROR_TITLES) >= 200, f"Expected 200+ titles, got {len(HORROR_TITLES)}"


def pick_random_horror() -> str:
    """Return a randomly selected horror movie or game title."""
    return random.choice(HORROR_TITLES)
